version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=929311423122.dkr.ecr.us-east-1.amazonaws.com/testautomation
      - VERSION=1.0.0
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$VERSION.$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Testing the Docker images...
      - docker-compose run ruby cucumber
      - docker-compose down
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$VERSION.$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"testautomation-sample-marvin","imageUri":"%s"}]' $REPOSITORY_URI:$VERSION.$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json